config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from les2peresnoel import core

from .sites import manager_admin_site

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("vAbGuJwYJyTAck/bUzLQvA/", admin.site.urls),
    path("manager/", manager_admin_site.urls),
    # path("baton/", include("baton.urls")),
    path("", include("les2peresnoel.core.urls")),
    path("accounts/", include("allauth.urls")),
    # path("core/", include("les2peresnoel.core.urls")),
    path("marketplace/", include("les2peresnoel.marketplace.urls")),
    path("stores/", include("les2peresnoel.stores.urls")),
    path("providers/", include("les2peresnoel.providers.urls")),
    path("payments/", include("les2peresnoel.payments.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("login/", core.views.login, name="login"),
    path("licences/", include("les2peresnoel.licences.urls")),
]


# if settings.DEBUG:
if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/stores/urls.py
from django.urls import path

from . import views

app_name = "stores"

urlpatterns = [
    path("products", views.product_list, name="product_list"),
    path("products/create", views.product_create, name="product_create"),
    path("products/<pk>/details", views.OnProductDetailsView.as_view(), name="product_details"),
    path("products/<pk>/update", views.OnProductEditView.as_view(), name="product_edit"),
    path("products/<pk>/delete", views.OnProductDeleteView.as_view(), name="product_delete"),
    path("products/<pk>/add", views.OnProductAddView.as_view(), name="product_add"),
]

les2peresnoel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from core import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("boutique", views.boutique, name="boutique"),
    path("livre/<int:livre_id>/", views.livre, name="livre_detail"),
    path("musique/<int:musik_id>/", views.musique, name="musique_detail"),
    path("video/<int:video_id>/", views.video, name="video_detail"),
    path("signup", views.signup, name="signup"),
    path("evolution", views.evolution, name="evolution"),
    path("prqw2pn", views.prqw2pn, name="prqw2pn"),
    path("birth", views.birth, name="birth"),
    path("gallerie", views.gallerie, name="gallerie"),
    path("produits_noel", views.produits_noel, name="produits_noel"),
    path("produits_horsnoel", views.produits_horsnoel, name="produits_horsnoel"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/stores/models.py
from django.db import models
from model_utils.models import SoftDeletableModel, TimeStampedModel, UUIDModel


# Create your models here.
class Order(UUIDModel, TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        ACCEPTED = "ACCEPTED", "Accepted"
        REJECTED = "REJECTED", "Rejected"

    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.PENDING
    )
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    tva = models.DecimalField(max_digits=10, decimal_places=2)
    redevance = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_fees = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(null=True, blank=True)
    provider = models.ForeignKey(
        "providers.Provider",
        on_delete=models.CASCADE,
        related_name="orders",
    )

    def __str__(self):
        return f"Order {self.id} from {self.provider}"

    def accept(self):
        self.status = self.Status.ACCEPTED
        self.save()

    def reject(self):
        self.status = self.Status.REJECTED
        self.save()


class OrderItem(UUIDModel, TimeStampedModel):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
    )
    product = models.ForeignKey(
        "marketplace.Product",
        on_delete=models.CASCADE,
        related_name="orders",
    )
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity}x {self.product.name} for {self.order}"

    @property
    def get_total(self):
        return self.price * self.quantity

les2peresnoel/stores/views.py
import sweetify
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django_htmx.http import HttpResponseClientRedirect

from config.settings import SWEETIFY_TOAST_TIMER
from les2peresnoel.marketplace.forms import ProductForm, ProductAddForm
from les2peresnoel.marketplace.models import Product
from les2peresnoel.utils import render_block

from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.views import View

class SweetifyMixin:
    def notify_success(self, request, message):
        sweetify.toast(
            request=request,
            title="Succès",
            icon="success",
            text=message,
            timer=SWEETIFY_TOAST_TIMER,
        )

    def notify_error(self, request, message):
        sweetify.toast(
            request=request,
            title="Erreur",
            icon="error",
            text=message,
            timer=SWEETIFY_TOAST_TIMER,
        )

@login_required
def product_list(request):
    # breakpoint()
    products = Product.objects.filter(owner=request.user)
    # paginate by 20
    paginator = Paginator(products, 20)
    page = request.GET.get("page")
    form = ProductForm()
    products = paginator.get_page(page)
    return render(
        request, "stores/products/list.html", {
            "products": products, "form": form}
    )


@login_required
def product_create(request):
    product_form = ProductForm()
    if request.method == "POST":
        product_form = ProductForm(request.POST, request.FILES)
        try:
            if product_form.is_valid():
                product_form.instance.owner = request.user
                product_form.save()
                if request.htmx:
                    return HttpResponseClientRedirect(reverse("stores:product_list"))
            else:
                sweetify.toast(
                    request=request,
                    title="Erreur",
                    icon="error",
                    text=_("Erreur dans la création du produit"),
                    timer=SWEETIFY_TOAST_TIMER,
                )
        except Exception as e:
            # Todo :: Log the error with thw date it's occured
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création du produit"),
                timer=SWEETIFY_TOAST_TIMER,
            )
            raise e
    return render_block(
        "stores/products/list.html",
        "form_product_content",
        context={"form": product_form},
    )
    # return render(
    #     request, "stores/products/create.html", context={"form": product_form}
    # )


@login_required
def product_details(request, pk):
    product = get_object_or_404(Product, pk=pk)
    # product_images = ProductImage.objects.filter(product=product)
    return render(
        request,
        "stores/products/detail.html",
        context={"product": product},
    )


@login_required
def product_update(request, pk):
    product_form = ProductForm(
        request.POST, instance=get_object_or_404(Product, pk=pk))
    if request.method == "POST":
        if product_form.is_valid():
            product_form.save()
            sweetify.toast(
                request=request,
                title=_("Produit mis à jour"),
                icon="success",
                text=_("Le produit a bien été mis à jour"),
                timer=SWEETIFY_TOAST_TIMER,
            )
            return redirect("marketplace:detail_product", pk=pk)
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la mise à jour du produit"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    return render(
        request, "stores/products/update.html", context={"form": product_form}
    )


@login_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.delete()
        return redirect("stores:products")
    return render(request, "stores/products/delete.html", context={"product": product})


class OnProductAddView(SweetifyMixin, View):
    template_name = 'stores/products/partials/add.html'
    
    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs.get('pk'))
        form = ProductAddForm()
        return render(request, self.template_name, {'form': form, 'product': product})

    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs.get('pk'))
        form = ProductAddForm(request.POST)
        
        if form.is_valid():
            quantity = form.cleaned_data.get('quantity')
            product.quantity += quantity  # Ajoute la quantité au produit existant
            product.save()
            self.notify_success(request, "Quantité ajoutée avec succès.")
            return HttpResponseClientRedirect(reverse('stores:product_list'))
        
        self.notify_error(request, "Erreur lors de l'ajout de la quantité.")
        return self.render_to_response({'form': form, 'product': product})


class OnProductEditView(SweetifyMixin, UpdateView):
    model = Product
    template_name = 'stores/products/partials/edit.html'
    form_class = ProductForm
    success_url = reverse_lazy('stores:product_list')

    def form_valid(self, form):
        form.save()
        self.notify_success(self.request, "Produit mis à jour avec succès.")
        return HttpResponseClientRedirect(self.success_url)

    def form_invalid(self, form):
        self.notify_error(self.request, "Erreur lors de la mise à jour du produit.")
        return self.render_to_response({'form': form})


class OnProductDeleteView(SweetifyMixin, DeleteView):
    model = Product
    template_name = 'stores/products/partials/delete.html'
    success_url = reverse_lazy('stores:product_list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        self.notify_success(self.request, "Produit supprimé avec succès.")
        return HttpResponseClientRedirect(self.success_url)


class OnProductDetailsView(DetailView):
    model = Product
    template_name = 'stores/products/partials/details.html'

templates/stores/products/create.html
{% extends  'layouts/admin.html' %}

{% block content %}
	
{% endblock %}

templates/stores/products/detail.html
{% extends 'layouts/admin.html' %}

{% block content %}
	<div class="row">
    
    </div>
{% endblock %}

templates/stores/products/list.html
{% extends 'layouts/admin.html' %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="page-header-left d-flex align-items-center">
                    <div class="page-header-title">
                        <h5 class="m-b-10">{% translate 'Produits' %}</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a
                                href="{% url 'stores:product_list' %}">{% translate 'Liste' %}</a></li>
                        <li class="breadcrumb-item">{% translate 'Tout les produits' %}</li>
                    </ul>
                </div>
                <div class="page-header-right ms-auto">
                    <div class="page-header-right-items">
                        {% if request.user.can_manage_stock %}
                        <div class="d-flex align-items-center gap-2 page-header-right-items-wrapper">

                            <a href="javascript:void(0);" class="btn btn-md btn-primary" data-bs-target="#new-product"
                               data-bs-toggle="modal" hx-get="{% url 'stores:product_create' %}"
                               hx-target="#new-product-content" hx-swap="innerHTML" hx-trigger="click"
                            >
                                <i class="feather-plus me-2"></i>
                                <span>{% translate "Nouveau produit" %}</span>
                            </a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row my-4 container-fluid">
        <div class="col-xxl-12">
            <div class="card stretch stretch-full">
                <div class="card-header">
                    <h5 class="card-title">{% trans "Mes produits" %}</h5>
                    <div class="card-header-action">
                        <div class="card-header-btn">
                            {% comment %}<div data-bs-toggle="tooltip" title="" data-bs-original-title="Delete">
                                <a href="javascript:void(0);" class="avatar-text avatar-xs bg-danger"
                                   data-bs-toggle="remove"> </a>
                            </div>{% endcomment %}
                            <div data-bs-toggle="tooltip" title="" data-bs-original-title="Refresh">
                                <a href="javascript:void(0);" class="avatar-text avatar-xs bg-warning"
                                   data-bs-toggle="{% translate "Rafraichir" %}"> </a>
                            </div>
                            <div data-bs-toggle="tooltip" title="" data-bs-original-title="Maximize/Minimize">
                                <a href="javascript:void(0);" class="avatar-text avatar-xs bg-success"
                                   data-bs-toggle="{% translate "Étendre" %}"> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body custom-card-action p-0">
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr class="border-b">
                                <th scope="row">{% translate "Produit" %}</th>
                                <th>{% translate "Prix" %}</th>
                                {% comment %} <th>{% translate "Quantité" %}</th> {% endcomment %}
                                <th>{% translate "Date" %}</th>
                                <th>{% translate "Statut" %}</th>
                                <th class="text-end">{% translate "Actions" %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for product in products %}
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center gap-3">
                                            <div class="avatar-image">
                                                <img src="{{ product.image.url }}" alt="" class="img-fluid">
                                            </div>
                                            <a href="{{ product.get_details_for_provider_url }}">
                                                <span class="d-block">{{ product.name }}</span>
                                                <span class="fs-12 d-block fw-normal text-muted">{{ product.categories.all }}</span>
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="badge bg-gray-200 text-dark">{{ product.price }} €</span>
                                    </td>
                                    {% comment %} <td>
                                        <span class="text-dark">{{ product.quantity }}</span>
                                    </td> {% endcomment %}
                                    <td>{{ product.created }}</td>
                                    <td>
                                        <span class="badge bg-soft-success text-{{ product.is_available | yesno:"success,danger" }}">{{ product.is_available | yesno:"En stock,Rupture" }}</span>
                                    </td>
                                    <td class="text-end">
                                        <div class="dropdown">
                                            <a href="#product-actions" data-bs-toggle="dropdown">
                                                <i class="feather-more-vertical"></i>
                                            </a>
                                            <ul class="dropdown-menu dropdown-menu-end" id="product-actions">
                                                {% comment %} <li>
                                                    <a class="dropdown-item" href="#" 
                                                       hx-get="{% url 'stores:product_add' product.id %}"
                                                       hx-target="#modal-content"
                                                       hx-trigger="click"
                                                       data-bs-toggle="modal"
                                                       data-bs-target="#productModal">
                                                        <i class="feather-plus"></i> {% translate "Ajouter" %}
                                                    </a>    
                                                </li> {% endcomment %}
                                                {% if request.user.can_manage_stock %}
                                                <li>
                                                    <a class="dropdown-item" href="#"
                                                       hx-get="{% url 'stores:product_edit' product.id %}"
                                                       hx-target="#modal-content"
                                                       hx-trigger="click"
                                                       data-bs-toggle="modal"
                                                       data-bs-target="#productModal">
                                                        <i class="feather-edit"></i> {% translate "Modifier" %}
                                                    </a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="#"
                                                       hx-get="{% url 'stores:product_delete' product.id %}"
                                                       hx-target="#modal-content"
                                                       hx-trigger="click"
                                                       data-bs-toggle="modal"
                                                       data-bs-target="#productModal">
                                                        <i class="feather-trash-2"></i> {% translate "Supprimer" %}
                                                    </a>
                                                </li>
                                                {% comment %} <li>
                                                    <a class="dropdown-item" href="#"
                                                       hx-get="{% url 'stores:product_details' product.id %}"
                                                       hx-target="#modal-content"
                                                       hx-trigger="click"
                                                       data-bs-toggle="modal"
                                                       data-bs-target="#productModal">
                                                        <i class="feather-eye"></i> 
                                                        {% translate "Détails" %}
                                                    </a>
                                                </li> {% endcomment %}
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <ul class="list-unstyled d-flex align-items-center gap-2 mb-0 pagination-common-style">
                        {% if products.has_previous %}
                            <li>
                                <a href="?page={{ products.previous_page_number }}"><i class="bi bi-arrow-left"></i></a>
                            </li>
                        {% endif %}
                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li><a href="?page={{ num }}" class="active">{{ num }}</a></li>
                            {% elif num > products.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- Lien vers la page suivante -->
                        {% if products.has_next %}
                            <li>
                                <a href="?page={{ products.next_page_number }}"><i class="bi bi-arrow-right"></i></a>
                            </li>
                       {% comment %} {% else %}
                            <li class="disabled"><span>Suivant &raquo;</span></li>{% endcomment %}
                        {% endif %}

                       {% comment %} <li><a href="javascript:void(0);">2</a></li>
                        <li>
                            <a href="javascript:void(0);"><i class="bi bi-dot"></i></a>
                        </li>
                        <li><a href="javascript:void(0);">8</a></li>
                        <li><a href="javascript:void(0);">9</a></li>{% endcomment %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modal %}
    <div class="modal" tabindex="-1" id="new-product">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% translate 'Ajouter un nouveau produit' %}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="new-product-content">
                    {% block form_product_content %}
                        <form hx-post="{% url 'stores:product_create' %}" hx-target="#new-product-content"
                              hx-swap="innerHTML" hx-encoding="multipart/form-data">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">{% translate 'Fermer' %}</button>
                                <button type="submit" class="btn btn-primary">{% translate 'Enregistrer' %}</button>
                            </div>
                        </form>
                    {% endblock %}
                </div>

            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="productModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                {% comment %} <div class="modal-header">
                    <h5 class="modal-title" id="productModalLabel">{% translate "Action sur le produit" %}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div> {% endcomment %}
                <div class="modal-body" id="modal-content">
                    <!-- Le contenu sera chargé ici par HTMX -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/stores/products/update.html
{% extends 'layouts/admin.html' %}

{% block content %}
	
{% endblock %}