config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from les2peresnoel import core

from .sites import manager_admin_site

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("vAbGuJwYJyTAck/bUzLQvA/", admin.site.urls),
    path("manager/", manager_admin_site.urls),
    # path("baton/", include("baton.urls")),
    path("", include("les2peresnoel.core.urls")),
    path("accounts/", include("allauth.urls")),
    # path("core/", include("les2peresnoel.core.urls")),
    path("marketplace/", include("les2peresnoel.marketplace.urls")),
    path("stores/", include("les2peresnoel.stores.urls")),
    path("providers/", include("les2peresnoel.providers.urls")),
    path("payments/", include("les2peresnoel.payments.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("login/", core.views.login, name="login"),
    path("licences/", include("les2peresnoel.licences.urls")),
]


# if settings.DEBUG:
if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/marketplace/urls.py
from django.urls import path, re_path

from . import views

app_name = "marketplace"

urlpatterns = [
    # Products
    path("", views.home, name="home"),
    path(
        "products",
     views.list_product, 
     name="products"
     ),
    path("products/create", views.create_product, name="create_product"),
    path(
        "products/<int:pk>/update", 
        views.update_product, 
        name="update_product"
    ),
    path(
        "products/<int:pk>/delete", 
        views.delete_product, 
        name="delete_product"
    ),
    path(
        "products/<int:pk>/detail", 
        views.detail_product, 
        name="detail_product"
    ),
    # Categories
    path(
        "categories", 
        views.list_category, 
        name="categories"
    ),
    path(
        "categories/create", 
        views.create_category, 
        name="create_category"
    ),
    path(
        "categories/<int:pk>/update", 
        views.update_category, 
        name="update_category"
    ),
    path(
        "categories/<int:pk>/delete", 
        views.delete_category, 
        name="delete_category"
    ),
    path(
        "categories/<int:pk>/detail", 
        views.detail_category, 
        name="detail_category"
    ),
    # DASHBOARD
    path(
        "dashboard/", 
        views.dashboard, 
        name="dashboard"
    ),
    path(
        "add_to_cart/<product_id>", 
        views.add_product, 
        name="add_to_cart"
    ),
    path(
        "update_cart_count", 
        views.update_cart_count, 
        name="update_cart_count"
    ),
    path(
        "update_cart", 
        views.update_cart, 
        name="update_cart"
    ),
    path(
        "remove_product",
        views.remove_product, 
        name="remove_product"
    ),

    # Checkout

    path(
        "checkout/",
        views.CheckoutView.as_view(),
        name="checkout"
    ),
    path(
        "update_checkout",
        views.update_checkout,
        name="update_checkout"
    ),

    path(
        "simple_checkout/<product_id>",
        views.simple_checkout,
        name="simple_checkout"
    ),
    # Orders
    path(
        'orders',
        views.order_list,
        name="order_list"
    ),
    path(
        'orders/<pk>',
        views.order_details,
        name="order_detail"
    ),
    path(
        'orders/<tracking_id>/tracking',
        views.order_tracking,
        name="order_tracking"
    ),

    path(
        'categories/<int:pk>/products', 
        views.list_product_by_category, 
        name='list_product_by_category'
    ),
]

les2peresnoel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from core import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("boutique", views.boutique, name="boutique"),
    path("livre/<int:livre_id>/", views.livre, name="livre_detail"),
    path("musique/<int:musik_id>/", views.musique, name="musique_detail"),
    path("video/<int:video_id>/", views.video, name="video_detail"),
    path("signup", views.signup, name="signup"),
    path("evolution", views.evolution, name="evolution"),
    path("prqw2pn", views.prqw2pn, name="prqw2pn"),
    path("birth", views.birth, name="birth"),
    path("gallerie", views.gallerie, name="gallerie"),
    path("produits_noel", views.produits_noel, name="produits_noel"),
    path("produits_horsnoel", views.produits_horsnoel, name="produits_horsnoel"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/marketplace/forms.py
from django.forms import ModelForm, widgets, Form, IntegerField, NumberInput

from .models import Category, Product, ProductImage, Checkout

from django.utils.translation import gettext_lazy as _


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        exclude = ("id", "created", "updated", "slug")


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ("id", "created", "updated", "slug", "is_removed", "owner", "quantity")
        widgets = {
            "category": widgets.CheckboxSelectMultiple(),
            "description": widgets.Textarea(attrs={"rows": 3}),
        }


class ProductAddForm(Form):
    quantity = IntegerField(
        label=_("Quantité"),
        initial=1,
        min_value=1,
        widget=NumberInput(attrs={"class": "form-control"}),
    )

class ProductImageForm(ModelForm):
    class Meta:
        model = ProductImage
        exclude = (
            "id",
            "created",
            "updated",
        )


class ProductImageSimpleForm(ModelForm):
    class Meta:
        model = ProductImage
        exclude = ("id", "created", "updated", "product")


class CheckoutForm(ModelForm):
    class Meta:
        model = Checkout
        exclude = ('id', 'created', 'updated')

les2peresnoel/marketplace/views.py
import sweetify
from dj_shop_cart.cart import get_cart_class
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.transaction import atomic as atomic_transaction
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.views import View
from django.views.decorators.http import require_POST
from django_htmx.http import HttpResponseClientRedirect, trigger_client_event
from render_block import render_block_to_string

from ..core.views import send_order_confirmation_email
from ..utils import render_block
from .forms import *
from .models import *
from .models import Product

SWEETIFY_TOAST_TIMER = settings.SWEETIFY_TOAST_TIMER


# Create your views here.


Cart = get_cart_class()


def home(request):
    products = (
        Product.get_available()
    )  # .only('pk', 'name', 'category', 'price', 'image')
    try:
        max_price = max([product.price for product in products])
    except:
        max_price = 0
    try:
        min_price = min([product.price for product in products])
    except:
        min_price = 0

    products = (
        products.filter(category__slug__icontains="bonheur")
        .exclude(media="")
        .distinct()
    )
    filter_categories_slugs = []
    if request.htmx:
        # breakpoint()
        for item in request.GET:
            if item.startswith("filter_category_"):
                filter_categories_slugs.append(request.GET.get(item))
        if filter_categories_slugs != []:
            products = products.filter(category__slug__in=filter_categories_slugs)

        filter_price_from = int(request.GET.get("filter_price_from") or 0)
        filter_price_to = int(request.GET.get("filter_price_to") or 0)
        if (
            filter_price_from != 0
            and filter_price_to != 0
            and filter_price_from < filter_price_to
        ):
            products = products.filter(
                price__gte=filter_price_from, price__lte=filter_price_to
            )
    paginator = Paginator(products, 9)
    page = request.GET.get("page")
    form = ProductForm()
    products = paginator.get_page(page)
    _context = {
        "categories": Category.objects.only("name", "cover_image", "slug").filter(
            slug__icontains="bonheur"
        ),
        "all_categories": Category.objects.only("name", "cover_image", "slug").filter(
            parent__isnull=True
        ),
        "products": products,
        "filter_datas": {
            "min_price": int(min_price),
            "start_min_price": 10,
            "max_price": int(max_price),
            "start_max_price": 90,
            "filter_categorie_slug": filter_categories_slugs,
        },
    }
    if request.htmx:
        return render_block("marketplace/home.html", "product_list", _context)
    return render(request, "marketplace/home.html", context=_context)


@require_POST
def add_product(request: HttpRequest, product_id: int, from_cart=False):
    product = get_object_or_404(Product.objects.all(), pk=product_id)
    # breakpoint()
    quantity = int(request.POST.get("quantity", default=1))
    source = request.POST.get("source")
    cart = Cart.new(request)
    # get the provider of the first product in cart
    # breakpoint()
    if cart.count > 0:
        first_product = cart.products[0]
        existing_provider = first_product.owner
    else:
        existing_provider, first_product = None, None

    if not first_product or (
        (not first_product.media or not product.media)
        and (first_product.media or product.media)
    ):
        sweetify.warning(
            request,
            title=_("Information"),
            text=_(
                "Vous ne pouvez pas mélanger les produits numériques et physiques dans le même panier \n"
            ),
            button=_("Compris !"),
            persistent=True,
            icon="info",
        )
        return HttpResponseClientRedirect(reverse("marketplace:home"))
    if existing_provider and existing_provider != product.owner:
        sweetify.warning(
            request,
            # title=_("Erreur !"),
            title=_("Information"),
            icon="info",
            text=_(
                "Vous ne pouvez pas ajouter des produits de différents fournisseurs dans le même panier \n"
                # "Terminer votre commande ou vider votre panier"
            ),
            button=_("Compris !"),
            # timer=SWEETIFY_TOAST_TIMER,
            persistent=True,
        )
        return HttpResponseClientRedirect(reverse("marketplace:home"))
    # else:
    #     provider = product.owner

    cart.add(product, quantity=quantity)
    sweetify.toast(
        request,
        title="Produit ajouté",
        icon="success",
        text="Produit ajouté avec succès !",
    )
    messages.success(request, message="Produit ajouté avec succès !")
    _context = {"cart": cart}
    if source == "cart":
        response = render_block("layouts/marketplace.html", "cart", _context)
    elif source == "checkout":
        response = render_block(
            "layouts/marketplace.html", "checkout_summary", _context
        )
    else:
        response = render_block("layouts/marketplace.html", "cart_count", _context)
        # response = TemplateResponse(request, "layouts/marketplace.html", _context)

    return trigger_client_event(response=response, name="update_cart", after="receive")


@require_POST
def remove_product(request: HttpRequest):
    # breakpoint()
    item_id = request.POST.get("item_id")
    quantity = int(request.POST.get("quantity", default=1))
    source = request.POST.get("source")
    cart = Cart.new(request)
    _context = {"cart": cart}
    cart.remove(item_id=item_id, quantity=quantity)
    if source and source == "cart":
        return render_block("layouts/marketplace.html", "cart", _context)
    if source and source == "checkout":
        # Todo: Load TVA from settings
        return render_block("layouts/marketplace.html", "checkout_summary", _context)
    return render_block("layouts/marketplace.html", "cart", _context)


@require_POST
def empty_cart(request: HttpRequest):
    Cart.new(request).empty()
    ...


def list_category(request):
    if request.method == "POST":
        category_form = CategoryForm(request.POST)
        if category_form.is_valid():
            category_form.save()
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création de la catégorie"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    categories = Category.objects.all()
    return render(
        request, "marketplace/categories/list.html", {"categories": categories}
    )


@login_required
def create_category(request):
    category_form = CategoryForm(request.POST)
    if request.method == "POST":
        if category_form.is_valid():
            category_form.save()
            sweetify.toast(
                request=request,
                title=_("Catégorie créée"),
                icon="success",
                text=_("La catégorie a bien été crée"),
                timer=SWEETIFY_TOAST_TIMER,
            )
            return redirect("marketplace:create_category")
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création de la catégorie"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    return render(
        request, "marketplace/categories/create.html", context={"form": category_form}
    )


def detail_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(
        request, "marketplace/categories/detail.html", context={"category": category}
    )


@login_required
def update_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category_form = CategoryForm(request.POST, instance=category)
    if request.method == "POST":
        if category_form.is_valid():
            category_form.save()
            sweetify.toast(
                request=request,
                title=_("Catégorie mise à jour"),
                icon="success",
                text=_("La catégorie a bien été mise à jour"),
                timer=SWEETIFY_TOAST_TIMER,
            )
            return redirect("marketplace:detail_category")
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création de la catégorie"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    return render(
        request, "marketplace/categories/update.html", context={"form": category_form}
    )


@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        category.delete()
        return redirect("marketplace:categories")
    return render(
        request, "marketplace/categories/delete.html", context={"category": category}
    )


def list_product(request):
    products = Product.objects.filter(user=request.user)
    # paginate by 20
    paginator = Paginator(products, 20)
    page = request.GET.get("page")
    products = paginator.get_page(page)
    return render(request, "marketplace/products/list.html", {"products": products})


def detail_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product_images = ProductImage.objects.filter(product=product)
    return render(
        request,
        "marketplace/products/detail.html",

templates/marketplace/products/list.html
{% extends 'layouts/marketplace.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <section class="container py-5 mt-5 mb-lg-4 mb-xl-5" >
        <!-- Breadcrumb -->
        <nav aria-label="breadcrumb">
            <ol class="pt-lg-3 pb-2 breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'marketplace:home' %}"> {% translate 'Accueil' %} </a>
                </li>
                {% if category  and category.parent %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'marketplace:list_product_by_category' category.parent.pk %}"> {{category.parent.name}} </a>
                    </li>
                {% endif %}
                <li class="breadcrumb-item active" aria-current="page"> {{category.name}} </li>
            </ol>
        </nav> 

        {% if categories %}
        <div class="category-area2">
            <div class="container">
                <h3 class="text-center">{% translate "Autres Catégories" %}</h3>
                <div class="row">
                    {% for category in categories %}
                        <div class="col">
                            <a href="{% url 'marketplace:list_product_by_category' category.pk %}">
                                <div class="category-info">
                                    <div class="icon">
                                        <img src="{{category.cover}}" alt="">
                                    </div>
                                    <div class="content">
                                    <h5 class="text-muted">{{category.name}}</h5>
                                    {% comment %} <p>{{category.items_count}} {% translate "Articles" %}</p> {% endcomment %}
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        
        <h3 class="pb-2 pb-sm-3 text-center mt-5 mb-5">{% translate 'Nos produits' %}</h3>
        <section class="container">
            <div class=" row pb-2 pb-sm-4">
            <div>
                <!-- Active filters + Sorting -->
                <div class="d-flex align-items-start justify-content-between mb-4">

                </div>
                <div class="row container row-cols-1 row-cols-sm-2 row-cols-md-3 g-4" id="product-list">
                    {% block product_list %}
                    {% for product in products %}
                        <div class="col pb-2 pb-sm-3 d-flex align-items-stretch" >
                            <div class="card-hover position-relative bg-secondary rounded-1 p-3 mb-4 flex-grow-1 d-flex flex-column">
                                <div>
                                    <a href="{{ product.get_absolute_url }}">
                                        <div class="p-2 p-xl-4">
                                            <img class="d-block mx-auto" src="{{ product.image.url }}" width="226" alt="Product">
                                        </div>
                                    </a>
                                </div>
                                <div class="mt-auto">
                                    <div class="d-flex mb-1">
                                        <h3 class="h6 mb-0">
                                            <a href="#">{{ product.name }}</a>
                                        </h3>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <span class="me-2">{{ product.price }}€</span>
                                        <div class="nav ms-auto" data-bs-toggle="tooltip"
                                            data-bs-template="<div class='tooltip fs-xs' role='tooltip'><div class='tooltip-inner bg-light text-body-secondary p-0'></div></div>"
                                            data-bs-placement="left" title="{% translate 'Ajouter au panier' %}">
                                            {% if product.media %}
                                                {% if product.price == 0 %}
                                                    <a class="py-2 px-2 btn btn-sm btn-outline-primary w-100 w-lg-auto me-2" download="{{product.name}}" href="{{product.media.url}}"
                                                    aria-label="{% translate 'Télécharger' %}"
                                                    {% comment %} hx-post="{% url 'marketplace:add_to_cart' product_id=product.pk %}" {% endcomment %}
                                                    {% comment %} hx-target="#cart-count" {% endcomment %}
                                                    {% comment %} hx-trigger="click" hx-swap="innerHTML" {% endcomment %}
                                                    >
                                                    <i class="ai-download"> </i>
                                                    {% translate "Télécharger" %}
                                                    </a>
                                                {% else %}
                                                    <a class="py-2 px-2 btn btn-sm btn-outline-primary w-100 w-lg-auto me-2" href="#"
                                                    aria-label="{% translate 'Ajouter au panier' %}"
                                                    hx-post="{% url 'marketplace:add_to_cart' product_id=product.pk %}"
                                                    hx-target="#cart-count"
                                                    hx-trigger="click" hx-swap="innerHTML">
                                                    <i class="ai-cart"> </i>
                                                    {% translate " Ajouter au panier" %}
                                                    </a>
                                                {% endif %}                                            
                                            {% else %}
                                            <a class="py-2 px-2 btn btn-sm btn-outline-primary w-100 w-lg-auto me-2" 
                                            aria-label="{% translate 'Commander' %}"
                                            href="{% url 'marketplace:simple_checkout' product_id=product.pk %}">
                                            <i class="fa fa-shopping-bag"> </i>  &nbsp;
                                            {% translate "Commander" %}
                                            </a>        
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% endblock product_list %}
                </div>

                

                <!-- Pagination -->
                <div class="row gy-3 align-items-center pt-3 pt-sm-4 mt-md-2">
                    {% comment %} <div class="col col-md-4 col-6 order-md-1 order-1">
                        <div class="d-flex align-items-center">
                            <span class="text-body-secondary fs-sm">{% translate "Afficher" %}</span>
                            <select class="form-select form-select-flush w-auto">
                                <option value="12">12</option>
                                <option value="18">18</option>
                                <option value="24">24</option>
                                <option value="30">30</option>
                            </select>
                        </div>
                    </div> {% endcomment %}
                    <div class="col col-md-4 col-12 order-md-2 order-3 text-center">
                        {% if products.has_next %}
                        <a href="?page={{ products.next_page_number }}" class="btn btn-primary w-md-auto w-100" type="button">{% translate 'Voir plus' %}</a>
                        {% endif %}
                    </div>
                    <div class="col col-md-4 col-6 order-md-3 order-2">
                        <nav aria-label="Page navigation">
                            <ul class="pagination pagination-sm justify-content-end">
                                {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link bg-secondary text-white" href="?page={{ products.previous_page_number }}"><i class="bi bi-arrow-left"></i></a>
                            </li>
                        {% endif %}
                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li class="page-item page-active"><a class="page-link bg-primary text-white" href="?page={{ num }}" class="active">{{ num }}</a></li>
                            {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- Lien vers la page suivante -->
                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link bg-secondary text-white"  href="?page={{ products.next_page_number }}"><i class="bi bi-arrow-right"></i></a>
                            </li>
                       {% comment %} {% else %}
                            <li class="disabled"><span>Suivant &raquo;</span></li>{% endcomment %}
                        {% endif %}
                        
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        </section>
        
    </section>
{% endblock %}