config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from les2peresnoel import core

from .sites import manager_admin_site

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("vAbGuJwYJyTAck/bUzLQvA/", admin.site.urls),
    path("manager/", manager_admin_site.urls),
    # path("baton/", include("baton.urls")),
    path("", include("les2peresnoel.core.urls")),
    path("accounts/", include("allauth.urls")),
    # path("core/", include("les2peresnoel.core.urls")),
    path("marketplace/", include("les2peresnoel.marketplace.urls")),
    path("stores/", include("les2peresnoel.stores.urls")),
    path("providers/", include("les2peresnoel.providers.urls")),
    path("payments/", include("les2peresnoel.payments.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("login/", core.views.login, name="login"),
    path("licences/", include("les2peresnoel.licences.urls")),
]


# if settings.DEBUG:
if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/marketplace/urls.py
from django.urls import path, re_path

from . import views

app_name = "marketplace"

urlpatterns = [
    # Products
    path("", views.home, name="home"),
    path(
        "products",
     views.list_product, 
     name="products"
     ),
    path("products/create", views.create_product, name="create_product"),
    path(
        "products/<int:pk>/update", 
        views.update_product, 
        name="update_product"
    ),
    path(
        "products/<int:pk>/delete", 
        views.delete_product, 
        name="delete_product"
    ),
    path(
        "products/<int:pk>/detail", 
        views.detail_product, 
        name="detail_product"
    ),
    # Categories
    path(
        "categories", 
        views.list_category, 
        name="categories"
    ),
    path(
        "categories/create", 
        views.create_category, 
        name="create_category"
    ),
    path(
        "categories/<int:pk>/update", 
        views.update_category, 
        name="update_category"
    ),
    path(
        "categories/<int:pk>/delete", 
        views.delete_category, 
        name="delete_category"
    ),
    path(
        "categories/<int:pk>/detail", 
        views.detail_category, 
        name="detail_category"
    ),
    # DASHBOARD
    path(
        "dashboard/", 
        views.dashboard, 
        name="dashboard"
    ),
    path(
        "add_to_cart/<product_id>", 
        views.add_product, 
        name="add_to_cart"
    ),
    path(
        "update_cart_count", 
        views.update_cart_count, 
        name="update_cart_count"
    ),
    path(
        "update_cart", 
        views.update_cart, 
        name="update_cart"
    ),
    path(
        "remove_product",
        views.remove_product, 
        name="remove_product"
    ),

    # Checkout

    path(
        "checkout/",
        views.CheckoutView.as_view(),
        name="checkout"
    ),
    path(
        "update_checkout",
        views.update_checkout,
        name="update_checkout"
    ),

    path(
        "simple_checkout/<product_id>",
        views.simple_checkout,
        name="simple_checkout"
    ),
    # Orders
    path(
        'orders',
        views.order_list,
        name="order_list"
    ),
    path(
        'orders/<pk>',
        views.order_details,
        name="order_detail"
    ),
    path(
        'orders/<tracking_id>/tracking',
        views.order_tracking,
        name="order_tracking"
    ),

    path(
        'categories/<int:pk>/products', 
        views.list_product_by_category, 
        name='list_product_by_category'
    ),
]

les2peresnoel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from core import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("boutique", views.boutique, name="boutique"),
    path("livre/<int:livre_id>/", views.livre, name="livre_detail"),
    path("musique/<int:musik_id>/", views.musique, name="musique_detail"),
    path("video/<int:video_id>/", views.video, name="video_detail"),
    path("signup", views.signup, name="signup"),
    path("evolution", views.evolution, name="evolution"),
    path("prqw2pn", views.prqw2pn, name="prqw2pn"),
    path("birth", views.birth, name="birth"),
    path("gallerie", views.gallerie, name="gallerie"),
    path("produits_noel", views.produits_noel, name="produits_noel"),
    path("produits_horsnoel", views.produits_horsnoel, name="produits_horsnoel"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/marketplace/models.py
import random
import string

from dj_shop_cart.cart import CartItem
from dj_shop_cart.protocols import Numeric
from django import forms
from django.conf import settings
from django.db import models
from django.db.models import (BooleanField, Case, Exists, OuterRef, Q, Value,
                              When)
from django.db.models.functions import Coalesce
from django.db.transaction import atomic as atomic_transaction
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import (SoftDeletableModel, StatusModel,
                                TimeStampedModel, UUIDModel)

from les2peresnoel.utils import generate_unique_slug

from ..payments.models import ProviderRefund
from ..users.models import User
from .models_abstract import Detail


# Create your models here.
class Category(Detail, TimeStampedModel, SoftDeletableModel):

    class Meta:
        verbose_name = _("Catégorie")
        verbose_name_plural = _("Catégories")

    slug = models.SlugField(max_length=100, editable=False)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    cover_image = models.ImageField(upload_to="categories/", blank=True, null=True)
    is_removed = models.BooleanField(
        default=False, verbose_name=_("Supprimé ?"), editable=False
    )

    @property
    def cover(self):
        return (
            self.cover_image.url
            if self.cover_image
            else settings.MARKETPLACE_DEFAULT.get("category_cover")
        )

    @property
    def items_count(self):
        return self.products.count

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = generate_unique_slug(Category, self.slug, slug_field="slug")
        super().save()


class Product(Detail, TimeStampedModel, SoftDeletableModel):

    class Meta:
        verbose_name = _("Produit")
        verbose_name_plural = _("Produits")

    slug = models.SlugField(max_length=100, editable=False)
    price = models.FloatField(verbose_name=_("Prix"))
    category = models.ManyToManyField(
        Category, verbose_name=_("Catégorie"), related_name="products"
    )
    quantity = models.IntegerField(verbose_name=_("Quantité"), default=1)
    external_link = models.URLField(help_text=_("Lien de dropshipping"), blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="products",
        editable=False,
    )
    image = models.ImageField(upload_to="products/", verbose_name=_("Couverture"))
    media = models.FileField(
        upload_to="products/media/", verbose_name=_("Média"), blank=True, null=True
    )
    is_removed = models.BooleanField(
        default=False, verbose_name=_("Supprimé ?"), editable=False
    )

    def __str__(self):
        return f"{self.name}-{self.category.name}"

    @classmethod
    def get_available(cls):
        from ..licences.models import \
            Licence  # Import local pour éviter les imports circulaires

        active_licence = Licence.objects.filter(
            provider=OuterRef("owner__providers"), is_active=True
        )

        return (
            cls.objects.select_related("owner")
            .annotate(
                owner_can_manage_stock=Case(
                    When(owner__is_superuser=True, then=Value(True)),
                    When(owner__is_staff=True, then=Value(True)),
                    When(Exists(active_licence), then=Value(True)),
                    default=Value(False),
                    output_field=BooleanField(),
                )
            )
            .filter(owner_can_manage_stock=True)
        )

    def get_price(self, item: CartItem) -> Numeric:
        return float(self.price)

    @property
    def is_available(self):
        return self.owner.can_manage_stock

    @property
    def media_url(self):
        return self.media.url if self.media else None

    @property
    def can_be_sold(self):
        # check if the product product.owner is a provider and has a licence
        return self.owner.profile.is_provider and self.owner.profile.licence.is_active

    def is_available_for_quantity(self, quantity):
        return self.quantity > quantity

    def get_details_for_provider_url(self):
        return reverse("stores:product_details", kwargs={"pk": self.pk})

    def get_absolute_url(self):
        return reverse("marketplace:detail_product", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.slug = generate_unique_slug(Product, self.slug, slug_field="slug")
        super().save()


class ProductImage(TimeStampedModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/")
    external_link = models.URLField(help_text=_("Lien externe"))
    is_cover = models.BooleanField(default=False)

    @property
    def get_url(self):
        return self.image.url or self.external_link

    @property
    def get_image(self):
        return self.image.url

    def __str__(self):
        return self.product.name


class Checkout(UUIDModel, TimeStampedModel):
    last_name = models.CharField(max_length=50, verbose_name=_("Nom"))
    first_name = models.CharField(max_length=50, verbose_name=_("Prénom(s)"))
    address = models.CharField(max_length=100, verbose_name=_("Adresse"))
    city = models.CharField(max_length=100, verbose_name=_("Ville"))
    zip_code = models.CharField(max_length=20, verbose_name=_("Code Postal"))
    country = models.CharField(max_length=50, verbose_name=_("Country"))
    email = models.EmailField(
        max_length=50, blank=True, verbose_name=_("Adresse E-mail")
    )
    phone_number = models.CharField(
        max_length=50, blank=True, verbose_name=_("Numero de téléphone")
    )
    order_notes = models.TextField(blank=True)
    payment_method = models.CharField(
        choices=[
            ("credit_card", "Credit Card"),
            ("paypal", "PayPal"),
            ("cash", "Cash"),
        ],
        verbose_name=_("Méthode de paiement"),
        max_length=12,
    )
    card_number = models.CharField(max_length=16, blank=True)
    card_expiry = models.CharField(max_length=5, blank=True)
    card_cvv = models.CharField(max_length=3, blank=True)
    paypal_address = models.CharField(_("Adresse PayPal"), max_length=50, blank=True)
    # pay_at_shipping = models.BooleanField(_("Paiement à la livraison"), default=False)


class Order(UUIDModel, TimeStampedModel, StatusModel):
    class Meta:
        verbose_name = _("Commande")
        verbose_name_plural = _("Commandes")

    STATUS = Choices("pending", "processing", "completed")

    last_name = models.CharField(_("Nom"), max_length=50, blank=True)
    first_name = models.CharField(_("Prénoms"), max_length=50, blank=True)
    email = models.EmailField(_("Adresse E-mail"), max_length=254, blank=True)
    total_ht = models.FloatField(_("Total Hors-Taxe"), editable=False)
    total_ttc = models.FloatField(_("Total TTC"), editable=False)
    total_tva = models.FloatField(_("Total TVA"), editable=False)
    shipping_amount = models.FloatField(
        _("Frais de livraison"), editable=False, default=0.0
    )
    checkout = models.ForeignKey(
        "Checkout",
        verbose_name=_("Checkout"),
        on_delete=models.SET_NULL,
        editable=False,
        null=True,
    )
    refund_generated = models.BooleanField(
        _("Redevance générée ?"), default=False, editable=False
    )
    tracking_number = models.CharField(
        _("N° de suivi"), max_length=10, blank=True, editable=False
    )
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Client"),
        on_delete=models.SET_NULL,
        null=True,
    )

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def get_payment_url(self):
        return reverse("payments:pay_tracked_order", kwargs={"order_pk": self.pk})

    def generate_refund(self):
        with atomic_transaction():
            if not self.refund_generated:
                items = self.orderitem_set.all()
                ProviderRefund.objects.bulk_create(
                    [
                        ProviderRefund(
                            order=self, provider=item.provider, order_item=item
                        )
                        for item in items
                    ]
                )
                self.refund_generated = True

    @property
    def generate_tracking_number(self):
        # Génère un numéro de suivi de 10 caractères alphanumériques
        tracking_number = "".join(
            random.choices(string.ascii_uppercase + string.digits, k=10)
        )
        return tracking_number

    @property
    def grouped_items(self):
        grouped = {}
        for item in self.orderitem_set.all():
            if item.product.id not in grouped:
                grouped[item.product.id] = {
                    "product": item.product,
                    "provider": item.provider,
                    "items": [],
                    "total_quantity": 0,
                    "total_price": 0,
                }
            grouped[item.product.id]["items"].append(item)
            grouped[item.product.id]["total_quantity"] += item.quantity
            grouped[item.product.id]["total_price"] += item.total
        return grouped.values()

    def save(self, *args, **kwargs):
        if not self.tracking_number:
            self.tracking_number = self.generate_tracking_number
        super().save()


class OrderItem(UUIDModel, TimeStampedModel):
    class Meta:
        verbose_name = _("Produit de commande")
        verbose_name_plural = _("Produits de commande")

    order = models.ForeignKey(
        Order,
        verbose_name=_("Commande"),
        on_delete=models.SET_NULL,
        null=True,

les2peresnoel/marketplace/forms.py
from django.forms import ModelForm, widgets, Form, IntegerField, NumberInput

from .models import Category, Product, ProductImage, Checkout

from django.utils.translation import gettext_lazy as _


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        exclude = ("id", "created", "updated", "slug")


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ("id", "created", "updated", "slug", "is_removed", "owner", "quantity")
        widgets = {
            "category": widgets.CheckboxSelectMultiple(),
            "description": widgets.Textarea(attrs={"rows": 3}),
        }


class ProductAddForm(Form):
    quantity = IntegerField(
        label=_("Quantité"),
        initial=1,
        min_value=1,
        widget=NumberInput(attrs={"class": "form-control"}),
    )

class ProductImageForm(ModelForm):
    class Meta:
        model = ProductImage
        exclude = (
            "id",
            "created",
            "updated",
        )


class ProductImageSimpleForm(ModelForm):
    class Meta:
        model = ProductImage
        exclude = ("id", "created", "updated", "product")


class CheckoutForm(ModelForm):
    class Meta:
        model = Checkout
        exclude = ('id', 'created', 'updated')

templates/marketplace/simple_checkout.html
{% extends "layouts/marketplace.html" %}
{% load i18n %}
{% load static %}

{% block extra_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@24.3.6/build/css/intlTelInput.css">
<link rel="stylesheet" href="{% static 'country/css/countrySelect.min.css' %}">
{% endblock extra_styles %}

{% block content %}
      <div class="d-none d-lg-block bg-secondary position-fixed top-0 start-0 h-100" style="width: 52.5%;"></div>

      <form class="needs-validation container position-relative z-2 pt-5 pb-lg-5 pb-md-4 pb-2" novalidate action="{% url "marketplace:checkout" %}" method=post>
        {% csrf_token %}
        <div class="row">
          <div class="col-lg-6">
            <nav aria-label="breadcrumb">
              <ol class="mt-5 pt-lg-3 pb-md-1 pb-lg-3 breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'marketplace:home' %}"> {% translate "Accueil" %} </a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{% url 'marketplace:home' %}"> {% translate "Marketplace" %} </a>
                </li>
                <li class="breadcrumb-item active" aria-current="page"> {% translate "Commande" %} </li>
              </ol>
            </nav>
            <h1 class="h2 pb-3"> {% translate "Commande / Checkout" %} </h1>
            <h3 class="fs-base fw-normal text-body text-uppercase pb-2 pb-sm-3">
              <span class="ms-1"> {% translate "Détails de la Commande" %} </span>
            </h3>
            <div class="row g-4 pb-4 pb-md-5 mb-3 mb-md-1">
              <div class="col-sm-6">
                <label class="form-label fs-base" for="id_fn"> {% translate "Nom" %} </label>
                <input class="form-control form-control-lg" name="last_name" type="text" placeholder=" {% translate "Entrez votre nom" %} " required id="id_fn">
              </div>
              <div class="col-sm-6">
                <label class="form-label fs-base" for="id_ln">{% translate "Prénom(s)" %}</label>
                <input class="form-control form-control-lg" name="first_name" type="text" placeholder=" {% translate "Entrez vos prénoms" %} " required id="id_ln">
              </div>
              <div class="col-sm-6">
                <label class="form-label fs-base" for="id_email">{% translate "Adresse E-mail" %}</label>
                <div class="position-relative"><i class="ai-mail fs-lg position-absolute top-50 start-0 translate-middle-y ms-3"></i>
                  <input class="form-control form-control-lg ps-5" name="email" type="email" placeholder="{% translate "Entrez votre adresse e-mail" %}" required id="id_email">
                </div>
              </div>
              <div class="col-sm-6">
                <label class="form-label fs-base" for="id_phone">{% translate "Numéro de téléphone" %}</label>
                <div class="position-relative">
                  <input class="form-control form-control-lg ps-5"  name="phone_number" type="tel" id="id_phone">
                </div>
              </div>
              <div class="col-12 d-flex flex-column">
                <label class="form-label fs-base" for="id_country">{% translate "Pays" %}</label>
                <input type="text" class="form-control form-control-lg" name="country" id="id_country" required>
                {% comment %} <select class="form-select form-select-lg" name="country" required id="id_country">
                  <option value="" selected disabled>{% translate "Choisissez le pays de livraison" %}</option>
                  <option value="Australia">Australie</option>
                  <option value="Belgium">Belgque</option>
                  <option value="Canada">Canada</option>
                  <option value="Denmark">France</option>
                  <option value="USA">USA</option>
                </select> {% endcomment %}
              </div>
              <div class="col-sm-6">
                <label class="form-label fs-base" for="id_city">{% translate "Ville" %}</label>
                <input class="form-control form-control-lg"  name="city" type="text" required id="id_city">
                {% comment %} <select class="form-select form-select-lg" name="city" required id="id_city">
                  <option value="" selected disabled>{% translate "Sélectionner une ville" %}</option>
                  <option value="Sydney">Sydney</option>
                  <option value="Brussels">Brussels</option>
                  <option value="Toronto">Toronto</option>
                  <option value="Copenhagen">Copenhagen</option>
                  <option value="New York">New York</option>
                </select> {% endcomment %}
              </div>
              <div class="col-sm-6">
                <label class="form-label fs-base" for="id_zip">{% translate "Code Postal" %}</label>
                <input class="form-control form-control-lg"  name="zip_code" type="text" placeholder="XXX-XXXX" required id="id_zip">
              </div>
              <div class="col-12">
                <label class="form-label fs-base" for="id_address">{% translate "Adresse de facturation" %}</label>
                <input class="form-control form-control-lg" name="address" type="text" required id="id_address">
              </div>
              <div class="col-12">
                <label class="form-label fs-base" for="id_notes">{% translate "Notes sur la commande" %} <span class="text-body-secondary">({% translate "Optionnel" %})</span></label>
                <textarea class="form-control form-control-lg" name="order_notes" rows="5" id="id_notes"></textarea>
              </div>
              <div class="col-12" id="id_shipping_adress">
              {% block shipping_adress %}
                <label class="form-label fs-base" for="id_address">{% translate "Adresse de livraison" %}</label>
                <input class="form-control form-control-lg" name="shipping_adress" type="text" required id="id_shipping-address">
              {% endblock shipping_adress %}
              </div>
            </div>
            <h3 class="fs-base fw-normal text-body text-uppercase mt-n4 mt-md-n3 pt-5 pb-2 pb-sm-3">
              <span class="ms-1">{% translate "Méthode de paiement" %}</span>
            </h3>
            <div class="form-check mb-4">
              <input class="form-check-input" type="radio" value="card" name="payment_method" checked id="card">
              <label class="form-check-label" for="card">
                <span>
                  <span class="d-block fs-base text-dark fw-medium mb-1">{% translate "Carte crédit" %}</span>
                  <span class="text-body">Nous acceptons, Mastercard, Visa</span>
                </span>
              </label>
            </div>
            <div class="form-check mb-4">
              <input class="form-check-input" value="paypal" type="radio" name="payment_method" id="paypal">
              <label class="form-check-label" for="paypal">
                <span>
                  <span class="d-block fs-base text-dark fw-medium mb-1">{% translate "Paypal" %}</span>
                  <span class="text-body">{% translate "Payez avec Paypal" %}</span>
                </span>
              </label>
            </div>
            <!-- Place an order button visible on screens > 991px -->
            <div class="d-none d-lg-block pt-5 mt-n3">
              <div class="form-check mb-4">
                <input class="form-check-input" type="checkbox" required id="save-info">
                <label class="form-check-label" for="save-info">
                  <span class="text-body-secondary"> 
                    {% translate "Vos informations personnelles seront utilisés pour traiter votre commande, pour améliorer votre expérience sur MPERESBONHEUR et pour vos futures commandes. Veuillez vous référer à notre politique de confideentialité, pour plus détails..." %}
                  </span>
                </label>
              </div>
              <button class="btn btn-lg btn-primary" type="submit">{% translate "Valider votre commande" %}</button>
            </div>
          </div>

          <!-- Order summary -->
          <div class="col-lg-5 offset-lg-1 pt-1" id="checkout" hx-target="this" hx-trigger="checkout_cart" hx-post="{% url "marketplace:update_checkout" %}" hx-swap="innerHTML">
            {% block checkout_summary %}
            <h2 class="pb-2 pt-md-2 my-4 mt-lg-5">
              Récapitulatif de la commande <br> <span class="fs-base fw-normal text-body-secondary">{% comment %} ({{cart.count}} {% translate "produits" %}){% endcomment %}</span>
            </h2>
           
            <div class="d-sm-flex align-items-center pb-4" id="cart-content">
                <a
                        class="d-inline-block flex-shrink-0 bg-secondary rounded-1 p-sm-2 p-md-3 mb-2 mb-sm-0"
                        href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}"
                                                                        width="110"
                                                                        alt="Product"></a>
                <div class="w-100 pt-1 ps-sm-4">
                    <div class="d-flex">
                        <div class="me-3">
                            <h3 class="h5 mb-2">
                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </h3>
                            <div class="d-sm-flex flex-wrap my-4">
                                <div class="text-body-secondary fs-sm me-3">
                                    {% translate "Quantité" %} : <span class="text-dark fw-medium"> 1</span>
                                </div>
                            </div>
                            <div class="d-sm-flex flex-wrap">
                                <div class="text-body-secondary fs-sm me-3">
                                    {% translate "Catégories" %} : <span class="text-dark fw-medium">
                                        {% for cat in product.category.all %}
                                        <span>{{ cat }} {{ forloop.last|yesno:', - ' }}</span>
                                        {% endfor %}
                                    </span>
                                </div>
                                
                            </div>
                        </div>
                        <div class="text-end ms-auto">
                            <div class="fs-5 mb-2">{{ product.price|floatformat:2 }} €</div>
                        </div>
                    </div>
                </div>
            </div>
            
            <ul class="list-unstyled py-3 mb-0">
              <li class="d-flex justify-content-between mb-2">
                {% translate "Total H.T" %}:<span class="fw-semibold ms-2">{{product.price|floatformat:2}} €</span>
              </li>
              {% comment %} <li class="d-flex justify-content-between mb-2">
                {% translate "Frais de livraison" %}:<span class="fw-semibold ms-2">{{shipping_fees}} €</span>
              </li> {% endcomment %}
            </ul>
            <div class="d-flex align-items-center justify-content-between border-top fs-xl pt-4">
              {% translate "Total T.T.C" %} (TVA 5.5%) :<span class="fs-3 fw-semibold text-dark ms-2">{{total_amount|floatformat:2}} €</span>
            </div>
            {% endblock checkout_summary %}
          </div>
        </div>

        <!-- Place an order button visible on screens < 992px -->
        <div class="d-lg-none pb-2 mt-2 mt-lg-0 pt-4 pt-lg-5">
          <div class="form-check mb-4">
            <input class="form-check-input" type="checkbox" checked id="save-info2">
            <label class="form-check-label" for="save-info2">
                <span class="text-body-secondary"> 
                    {% translate "Vos informations personnelles seront utilisés pour traiter votre commande, pour améliorer votre expérience sur MPERESBONHEUR et pour vos futures commandes. Veuillez vous référer à notre politique de confideentialité, pour plus détails..." %}
                  </span>
              </label>
          </div>
          <button class="btn btn-lg btn-primary w-100 w-sm-auto" type="submit">{% translate "Valider votre commande" %}</button>
        </div>
      </form>

      <script>
        document.addEventListener('htmx:update_checkout', function(){
            console.log("update_checkout")
        })
      </script>
      
{% endblock content %}

{% block extra_scripts %}
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/intl-tel-input@24.3.6/build/js/intlTelInput.min.js"></script>
 <script src="{% static 'country/js/countrySelect.min.js' %}"></script>
    <script>
      const input = document.querySelector("#id_phone");
      window.intlTelInput(input, {
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@24.3.6/build/js/utils.js",
      });
      $("#id_country").countrySelect();
    </script>

{% endblock extra_scripts %}