config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from les2peresnoel import core

from .sites import manager_admin_site

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("vAbGuJwYJyTAck/bUzLQvA/", admin.site.urls),
    path("manager/", manager_admin_site.urls),
    # path("baton/", include("baton.urls")),
    path("", include("les2peresnoel.core.urls")),
    path("accounts/", include("allauth.urls")),
    # path("core/", include("les2peresnoel.core.urls")),
    path("marketplace/", include("les2peresnoel.marketplace.urls")),
    path("stores/", include("les2peresnoel.stores.urls")),
    path("providers/", include("les2peresnoel.providers.urls")),
    path("payments/", include("les2peresnoel.payments.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("login/", core.views.login, name="login"),
    path("licences/", include("les2peresnoel.licences.urls")),
]


# if settings.DEBUG:
if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/marketplace/urls.py
from django.urls import path, re_path

from . import views

app_name = "marketplace"

urlpatterns = [
    # Products
    path("", views.home, name="home"),
    path(
        "products",
     views.list_product, 
     name="products"
     ),
    path("products/create", views.create_product, name="create_product"),
    path(
        "products/<int:pk>/update", 
        views.update_product, 
        name="update_product"
    ),
    path(
        "products/<int:pk>/delete", 
        views.delete_product, 
        name="delete_product"
    ),
    path(
        "products/<int:pk>/detail", 
        views.detail_product, 
        name="detail_product"
    ),
    # Categories
    path(
        "categories", 
        views.list_category, 
        name="categories"
    ),
    path(
        "categories/create", 
        views.create_category, 
        name="create_category"
    ),
    path(
        "categories/<int:pk>/update", 
        views.update_category, 
        name="update_category"
    ),
    path(
        "categories/<int:pk>/delete", 
        views.delete_category, 
        name="delete_category"
    ),
    path(
        "categories/<int:pk>/detail", 
        views.detail_category, 
        name="detail_category"
    ),
    # DASHBOARD
    path(
        "dashboard/", 
        views.dashboard, 
        name="dashboard"
    ),
    path(
        "add_to_cart/<product_id>", 
        views.add_product, 
        name="add_to_cart"
    ),
    path(
        "update_cart_count", 
        views.update_cart_count, 
        name="update_cart_count"
    ),
    path(
        "update_cart", 
        views.update_cart, 
        name="update_cart"
    ),
    path(
        "remove_product",
        views.remove_product, 
        name="remove_product"
    ),

    # Checkout

    path(
        "checkout/",
        views.CheckoutView.as_view(),
        name="checkout"
    ),
    path(
        "update_checkout",
        views.update_checkout,
        name="update_checkout"
    ),

    path(
        "simple_checkout/<product_id>",
        views.simple_checkout,
        name="simple_checkout"
    ),
    # Orders
    path(
        'orders',
        views.order_list,
        name="order_list"
    ),
    path(
        'orders/<pk>',
        views.order_details,
        name="order_detail"
    ),
    path(
        'orders/<tracking_id>/tracking',
        views.order_tracking,
        name="order_tracking"
    ),

    path(
        'categories/<int:pk>/products', 
        views.list_product_by_category, 
        name='list_product_by_category'
    ),
]

les2peresnoel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from core import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("boutique", views.boutique, name="boutique"),
    path("livre/<int:livre_id>/", views.livre, name="livre_detail"),
    path("musique/<int:musik_id>/", views.musique, name="musique_detail"),
    path("video/<int:video_id>/", views.video, name="video_detail"),
    path("signup", views.signup, name="signup"),
    path("evolution", views.evolution, name="evolution"),
    path("prqw2pn", views.prqw2pn, name="prqw2pn"),
    path("birth", views.birth, name="birth"),
    path("gallerie", views.gallerie, name="gallerie"),
    path("produits_noel", views.produits_noel, name="produits_noel"),
    path("produits_horsnoel", views.produits_horsnoel, name="produits_horsnoel"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

les2peresnoel/marketplace/forms.py
from django.forms import ModelForm, widgets, Form, IntegerField, NumberInput

from .models import Category, Product, ProductImage, Checkout

from django.utils.translation import gettext_lazy as _


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        exclude = ("id", "created", "updated", "slug")


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ("id", "created", "updated", "slug", "is_removed", "owner", "quantity")
        widgets = {
            "category": widgets.CheckboxSelectMultiple(),
            "description": widgets.Textarea(attrs={"rows": 3}),
        }


class ProductAddForm(Form):
    quantity = IntegerField(
        label=_("Quantité"),
        initial=1,
        min_value=1,
        widget=NumberInput(attrs={"class": "form-control"}),
    )

class ProductImageForm(ModelForm):
    class Meta:
        model = ProductImage
        exclude = (
            "id",
            "created",
            "updated",
        )


class ProductImageSimpleForm(ModelForm):
    class Meta:
        model = ProductImage
        exclude = ("id", "created", "updated", "product")


class CheckoutForm(ModelForm):
    class Meta:
        model = Checkout
        exclude = ('id', 'created', 'updated')

les2peresnoel/marketplace/views.py
import sweetify
from dj_shop_cart.cart import get_cart_class
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.transaction import atomic as atomic_transaction
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.views import View
from django.views.decorators.http import require_POST
from django_htmx.http import HttpResponseClientRedirect, trigger_client_event
from render_block import render_block_to_string

from ..core.views import send_order_confirmation_email
from ..utils import render_block
from .forms import *
from .models import *
from .models import Product

SWEETIFY_TOAST_TIMER = settings.SWEETIFY_TOAST_TIMER


# Create your views here.


Cart = get_cart_class()


def home(request):
    products = (
        Product.get_available()
    )  # .only('pk', 'name', 'category', 'price', 'image')
    try:
        max_price = max([product.price for product in products])
    except:
        max_price = 0
    try:
        min_price = min([product.price for product in products])
    except:
        min_price = 0

    products = (
        products.filter(category__slug__icontains="bonheur")
        .exclude(media="")
        .distinct()
    )
    filter_categories_slugs = []
    if request.htmx:
        # breakpoint()
        for item in request.GET:
            if item.startswith("filter_category_"):
                filter_categories_slugs.append(request.GET.get(item))
        if filter_categories_slugs != []:
            products = products.filter(category__slug__in=filter_categories_slugs)

        filter_price_from = int(request.GET.get("filter_price_from") or 0)
        filter_price_to = int(request.GET.get("filter_price_to") or 0)
        if (
            filter_price_from != 0
            and filter_price_to != 0
            and filter_price_from < filter_price_to
        ):
            products = products.filter(
                price__gte=filter_price_from, price__lte=filter_price_to
            )
    paginator = Paginator(products, 9)
    page = request.GET.get("page")
    form = ProductForm()
    products = paginator.get_page(page)
    _context = {
        "categories": Category.objects.only("name", "cover_image", "slug").filter(
            slug__icontains="bonheur"
        ),
        "all_categories": Category.objects.only("name", "cover_image", "slug").filter(
            parent__isnull=True
        ),
        "products": products,
        "filter_datas": {
            "min_price": int(min_price),
            "start_min_price": 10,
            "max_price": int(max_price),
            "start_max_price": 90,
            "filter_categorie_slug": filter_categories_slugs,
        },
    }
    if request.htmx:
        return render_block("marketplace/home.html", "product_list", _context)
    return render(request, "marketplace/home.html", context=_context)


@require_POST
def add_product(request: HttpRequest, product_id: int, from_cart=False):
    product = get_object_or_404(Product.objects.all(), pk=product_id)
    # breakpoint()
    quantity = int(request.POST.get("quantity", default=1))
    source = request.POST.get("source")
    cart = Cart.new(request)
    # get the provider of the first product in cart
    # breakpoint()
    if cart.count > 0:
        first_product = cart.products[0]
        existing_provider = first_product.owner
    else:
        existing_provider, first_product = None, None

    if not first_product or (
        (not first_product.media or not product.media)
        and (first_product.media or product.media)
    ):
        sweetify.warning(
            request,
            title=_("Information"),
            text=_(
                "Vous ne pouvez pas mélanger les produits numériques et physiques dans le même panier \n"
            ),
            button=_("Compris !"),
            persistent=True,
            icon="info",
        )
        return HttpResponseClientRedirect(reverse("marketplace:home"))
    if existing_provider and existing_provider != product.owner:
        sweetify.warning(
            request,
            # title=_("Erreur !"),
            title=_("Information"),
            icon="info",
            text=_(
                "Vous ne pouvez pas ajouter des produits de différents fournisseurs dans le même panier \n"
                # "Terminer votre commande ou vider votre panier"
            ),
            button=_("Compris !"),
            # timer=SWEETIFY_TOAST_TIMER,
            persistent=True,
        )
        return HttpResponseClientRedirect(reverse("marketplace:home"))
    # else:
    #     provider = product.owner

    cart.add(product, quantity=quantity)
    sweetify.toast(
        request,
        title="Produit ajouté",
        icon="success",
        text="Produit ajouté avec succès !",
    )
    messages.success(request, message="Produit ajouté avec succès !")
    _context = {"cart": cart}
    if source == "cart":
        response = render_block("layouts/marketplace.html", "cart", _context)
    elif source == "checkout":
        response = render_block(
            "layouts/marketplace.html", "checkout_summary", _context
        )
    else:
        response = render_block("layouts/marketplace.html", "cart_count", _context)
        # response = TemplateResponse(request, "layouts/marketplace.html", _context)

    return trigger_client_event(response=response, name="update_cart", after="receive")


@require_POST
def remove_product(request: HttpRequest):
    # breakpoint()
    item_id = request.POST.get("item_id")
    quantity = int(request.POST.get("quantity", default=1))
    source = request.POST.get("source")
    cart = Cart.new(request)
    _context = {"cart": cart}
    cart.remove(item_id=item_id, quantity=quantity)
    if source and source == "cart":
        return render_block("layouts/marketplace.html", "cart", _context)
    if source and source == "checkout":
        # Todo: Load TVA from settings
        return render_block("layouts/marketplace.html", "checkout_summary", _context)
    return render_block("layouts/marketplace.html", "cart", _context)


@require_POST
def empty_cart(request: HttpRequest):
    Cart.new(request).empty()
    ...


def list_category(request):
    if request.method == "POST":
        category_form = CategoryForm(request.POST)
        if category_form.is_valid():
            category_form.save()
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création de la catégorie"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    categories = Category.objects.all()
    return render(
        request, "marketplace/categories/list.html", {"categories": categories}
    )


@login_required
def create_category(request):
    category_form = CategoryForm(request.POST)
    if request.method == "POST":
        if category_form.is_valid():
            category_form.save()
            sweetify.toast(
                request=request,
                title=_("Catégorie créée"),
                icon="success",
                text=_("La catégorie a bien été crée"),
                timer=SWEETIFY_TOAST_TIMER,
            )
            return redirect("marketplace:create_category")
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création de la catégorie"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    return render(
        request, "marketplace/categories/create.html", context={"form": category_form}
    )


def detail_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(
        request, "marketplace/categories/detail.html", context={"category": category}
    )


@login_required
def update_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category_form = CategoryForm(request.POST, instance=category)
    if request.method == "POST":
        if category_form.is_valid():
            category_form.save()
            sweetify.toast(
                request=request,
                title=_("Catégorie mise à jour"),
                icon="success",
                text=_("La catégorie a bien été mise à jour"),
                timer=SWEETIFY_TOAST_TIMER,
            )
            return redirect("marketplace:detail_category")
        else:
            sweetify.toast(
                request=request,
                title="Erreur",
                icon="error",
                text=_("Erreur dans la création de la catégorie"),
                timer=SWEETIFY_TOAST_TIMER,
            )
    return render(
        request, "marketplace/categories/update.html", context={"form": category_form}
    )


@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        category.delete()
        return redirect("marketplace:categories")
    return render(
        request, "marketplace/categories/delete.html", context={"category": category}
    )


def list_product(request):
    products = Product.objects.filter(user=request.user)
    # paginate by 20
    paginator = Paginator(products, 20)
    page = request.GET.get("page")
    products = paginator.get_page(page)
    return render(request, "marketplace/products/list.html", {"products": products})


def detail_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product_images = ProductImage.objects.filter(product=product)
    return render(
        request,
        "marketplace/products/detail.html",

templates/marketplace/orders/list.html
{% extends 'layouts/admin.html' %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="page-header-left d-flex align-items-center">
                    <div class="page-header-title">
                        <h5 class="m-b-10">{% translate 'Commandes' %}</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a
                                href="{% url 'marketplace:order_list' %}">{% translate 'Liste' %}</a></li>
                        <li class="breadcrumb-item">{% translate 'Toutes les commandes' %}</li>
                    </ul>
                </div>
                <div class="page-header-right ms-auto">
                    <div class="page-header-right-items">
                        {% comment %}
                        <div class="d-flex d-md-none">
                            <a href="javascript:void(0)" class="page-header-right-close-toggle">
                                <i class="feather-arrow-left me-2"></i>
                                <span>Back</span>
                            </a>
                        </div>
                        {% endcomment %}
                    </div>
                    {% comment %}
                    <div class="d-md-none d-flex align-items-center">
                        <a href="javascript:void(0)" class="page-header-right-open-toggle">
                            <i class="feather-align-right fs-20"></i>
                        </a>
                    </div>
                    {% endcomment %}
                </div>
            </div>
        </div>
    </div>
    <div class="row my-4 container-fluid">
        <div class="col-xxl-12">
            <div class="card stretch stretch-full">
                <div class="card-header">
                    {% comment %} <h5 class="card-title">{% trans "Mes requêtes de licences" %}</h5> {% endcomment %}
                    <div class="card-header-action">
                        <div class="card-header-btn">
                            {% comment %}<div data-bs-toggle="tooltip" title="" data-bs-original-title="Delete">
                                <a href="javascript:void(0);" class="avatar-text avatar-xs bg-danger"
                                   data-bs-toggle="remove"> </a>
                            </div>{% endcomment %}
                            {% comment %} <div data-bs-toggle="tooltip" title="" data-bs-original-title="Refresh">
                                <a href="javascript:void(0);" class="avatar-text avatar-xs bg-warning"
                                   data-bs-toggle="{% translate "Rafraichir" %}"> </a>
                            </div>
                            <div data-bs-toggle="tooltip" title="" data-bs-original-title="Maximize/Minimize">
                                <a href="javascript:void(0);" class="avatar-text avatar-xs bg-success"
                                   data-bs-toggle="{% translate "Étendre" %}"> </a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
                <div class="card-body custom-card-action p-0">
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr class="border-b">
                                <th scope="row">{% translate "Client" %}</th>
                                <th>{% translate "Email" %}</th>
                                <th>{% translate "Total TTC" %}</th>
                                <th>{% translate "Date" %}</th>
                                <th class="text-end">{% translate "Détails" %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center gap-3">
                                            
                                            <a href="#">
                                                <span class="d-block">{{ order.get_full_name }}</span>
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="badge bg-gray-200 text-dark"><a href="mailto:{{ order.email }}">{{ order.email }}</a></span>
                                    </td>
                                    <td>
                                        <span class="text-dark">{{ order.total_ttc }}</span>
                                    </td>
                                    <td>{{ order.created }}</td>
                                    <td class="text-end">
                                        <a class="d-flex align-items-center gap-2 justify-content-end"
                                            href="#order-detail"
                                            hx-get="{% url 'marketplace:order_detail' order.id %}"
                                            hx-target="#order-detail-content"
                                            hx-trigger="click"
                                            hx-swap="outerHTML"
                                            data-bs-toggle="modal"
                                            >
                                            <i class="feather-eye"></i> 
                                            <span class="">{% translate "Détails" %}</span>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <ul class="list-unstyled d-flex align-items-center gap-2 mb-0 pagination-common-style">
                        {% if products.has_previous %}
                            <li>
                                <a href="?page={{ products.previous_page_number }}"><i class="bi bi-arrow-left"></i></a>
                            </li>
                        {% endif %}
                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li><a href="?page={{ num }}" class="active">{{ num }}</a></li>
                            {% elif num > products.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- Lien vers la page suivante -->
                        {% if products.has_next %}
                            <li>
                                <a href="?page={{ products.next_page_number }}"><i class="bi bi-arrow-right"></i></a>
                            </li>
                       {% comment %} {% else %}
                            <li class="disabled"><span>Suivant &raquo;</span></li>{% endcomment %}
                        {% endif %}

                       {% comment %} <li><a href="javascript:void(0);">2</a></li>
                        <li>
                            <a href="javascript:void(0);"><i class="bi bi-dot"></i></a>
                        </li>
                        <li><a href="javascript:void(0);">8</a></li>
                        <li><a href="javascript:void(0);">9</a></li>{% endcomment %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modal %}
    <div class="modal" tabindex="-1" id="order-detail">
        <div class="modal-dialog">
            <div class="modal-content">
                
                <div class="modal-header">
                    <h5 class="modal-title">{% translate 'Détails de la commande' %}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                {% block order_detail_content %}
                <div class="modal-body" id="order-detail-content">
                    {% for order_item in order.items.all %}
                        <div class="row">
                            <div class="col-md-6">
                                <p>{{ order_item.product.name }}</p>
                            </div>
                            <div class="col-md-6">
                                <p> X {{ order_item.quantity }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}